Manof provisioning, pull, push should use same repository
v3io/manof pull request #11
Opened 2019-03-07 14:16 UTC by liranbg

- Introducing `default_repository` 
- remote_image_name is a composition of repository+image_name whereas the repository is determined by the `default_repository` and the repository arg given by cli (repository arg is being prioritized over `default_repository`)
- `provision` command should use `manof pull` if no context is given
- `provision` command has tag-local set to True by default to have the exact same behavior and output between build,pull
- tag-local fix if repository is `docker.io` (since it is by default omitted, `docker rmi docker.io/X` == `docker rmi X`, and that can lead to the entire removal of the docker image)
- some indentation fixes
- some typos fixes

2019-03-08 18:02 UTC, omesser requested changes
Nicely done. Minor comments inside

2019-03-08 18:02 UTC, omesser commented on manof.py
> +                                   default=True,
If default is to tag, then this should be - skip-local-tagging with default false

2019-03-08 18:02 UTC, omesser commented on manof.py
> +                                   action='store_true')
Giving `store_true` arg with default true? then CLI can't turn this off, no? Am I wrong here?
I think this should be `--skip-tag-local` and default to `False` then

2019-03-08 18:02 UTC, omesser commented on manof/image.py
> +        self._logger.debug('Pushing',
Log only after checking the `skip_push` is not True. (avoid: 1: pushing, 2: skipping push - which might look awkward in logs)
Also please add `image_name`, `remote_image_name` to the log in line 273 to make it more informative if this log won't appear before it

2019-03-08 18:02 UTC, omesser commented on manof/image.py
> +        self._logger.debug('Pulling', remote_image_name=self.remote_image_name)
Log whether `self._args.tag_local` was requested as well here

2019-03-08 18:02 UTC, omesser commented on manof/image.py
> +            defer.returnValue(None)
Give the user a debug log to inform what'cha doin' here please

2019-03-08 18:02 UTC, omesser commented on manof/image.py
> +            # self._logger.warn('No remote repository was given, setting to \"docker.io\"')
I think this log should be uncommented, but debug

2019-03-10 10:16 UTC, liranbg commented on manof.py
> +                                   default=True,
Since `manof provision` uses `manof pull`, it has to be the same flag name

2019-03-10 10:16 UTC, liranbg commented on manof.py
> +                                   action='store_true')
`store_true` -> `False`
`store_false` -> `True`

2019-03-10 11:23 UTC, liranbg commented on manof.py
> +                                   default=True,
used 'dest' & changed flag name to '--skip-tag-local'

2019-03-11 13:49 UTC, omesser approved these changes

2019-03-11 13:50 UTC, merged